const PROVIDER_GOOGLE_GMAIL = 'google-gmail';
const PROVIDER_MICROSOFT_OUTLOOK = 'microsoft-outlook';
const PROVIDER_AMAZON_SNS = 'amazon-sns';

const CONNECTION_METHOD_OAUTH2 = 'oauth2';
const CONNECTION_METHOD_ACCESS_KEYS = 'access-keys';

const CONNECTED_APPLICATION_STATUS_DRAFT = 'draft';
const CONNECTED_APPLICATION_STATUS_CONNECTED = 'connected';

const SUPPORTED_PROVIDER_CONNECTIONS = {
  [PROVIDER_GOOGLE_GMAIL]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_MICROSOFT_OUTLOOK]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_AMAZON_SNS]: CONNECTION_METHOD_ACCESS_KEYS,
} as const;

type ProviderId = keyof typeof SUPPORTED_PROVIDER_CONNECTIONS;
type ConnectionMethod = (typeof SUPPORTED_PROVIDER_CONNECTIONS)[ProviderId];
type ConnectedApplicationStatus = typeof CONNECTED_APPLICATION_STATUS_DRAFT | typeof CONNECTED_APPLICATION_STATUS_CONNECTED;

export {
  CONNECTED_APPLICATION_STATUS_CONNECTED,
  CONNECTED_APPLICATION_STATUS_DRAFT,
  CONNECTION_METHOD_ACCESS_KEYS,
  CONNECTION_METHOD_OAUTH2,
  PROVIDER_AMAZON_SNS,
  PROVIDER_GOOGLE_GMAIL,
  PROVIDER_MICROSOFT_OUTLOOK,
  SUPPORTED_PROVIDER_CONNECTIONS,
};
export type { ConnectedApplicationStatus, ConnectionMethod, ProviderId };
