const DEFAULT_MAX_APPLICATIONS_PER_USER = '99';
const DEFAULT_MAX_API_KEYS_PER_APPLICATION = '5';
const DEFAULT_DEFAULT_API_KEY_EXPIRY_DAYS = '365';
const DEFAULT_MAX_API_KEY_EXPIRY_DAYS = '365';
const DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES = '15';

export {
  DEFAULT_DEFAULT_API_KEY_EXPIRY_DAYS,
  DEFAULT_MAX_API_KEY_EXPIRY_DAYS,
  DEFAULT_MAX_API_KEYS_PER_APPLICATION,
  DEFAULT_MAX_APPLICATIONS_PER_USER,
  DEFAULT_OAUTH2_STATE_EXPIRY_MINUTES,
};
